# Generated by Django 2.2 on 2019-04-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dianqi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, verbose_name='商品类别')),
                ('salesnum', models.IntegerField(default=0, verbose_name='商品销量')),
            ],
            options={
                'verbose_name': '电器销售管理',
                'verbose_name_plural': '电器销售管理',
                'db_table': 'dianqi',
            },
        ),
        migrations.CreateModel(
            name='yifu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, verbose_name='商品类别')),
                ('salesnum', models.IntegerField(default=0, verbose_name='商品销量')),
            ],
            options={
                'verbose_name': '衣服销售管理',
                'verbose_name_plural': '衣服销售管理',
                'db_table': 'yifu',
            },
        ),
    ]
